# -*- coding: utf-8 -*-
"""RestaurantOrderMgmt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb-ZQBV_r50xJlBuOTNShcKUbIQ_-W7d
"""

#dict for menu
menu = {
    'Pizza':40,
    'Pasta':50,
    'Burger':60,
    'Salad':70,
    'Coffe':80
}

print(menu)

print("welcome to Chataka Restaurant")
print("Pizz Rs40\n Pasta Rs50\n Burger Rs60\n Salad Rs70\n 'Coffe Rs80" )

from re import A
orderTotal = 0
item1 = input("Enter the name of item you want to order = ")
if item1 in menu:
   orderTotal += menu[item1]
   print("Your item {item1} has been added to your order")

else:
  print("Your item {item1} is not avilable yet")

anotherOrder = input("Do you want to addd another item? (Yes/No)")

if anotherOrder == "Yes":
   item2 = input("Enter second item =")
   if item2 in menu:
      orderTotal += menu[item2]
      print("Your item {item2} has been added to your order")
   else:
      print("Your item {item2} is not avilable yet")

print("Total amunt of order to pay is", {orderTotal})